#!/usr/bin/env node

var fs = require("fs"),
    print = require("sys").print,
    exec = require("child_process").exec,
    path = require("path"),
    root = __dirname,
    pwd = process.env.PWD;

if (process.argv.length == 2) {
    print("Requires 1 argument to define the folder name.\n");
    return;
}

var name = process.argv[2],
    path = pwd + "/" + name;

if (!fs.existsSync(path)) {
    fs.mkdirSync(path);
}

print("Copying files.\n");

exec("cp -rf " + root + "/base/. " + path, function() {
    print("Done.\n");

    print("Installing npm packages.\n");

    process.chdir(path);

    exec("npm install", function() {
        print("Installed npm packages.\n");

        print("Installing bower packages.\n");

        exec("node_modules/.bin/bower install", function() {
            print("Installed bower package.\n");

            print("Run 'cd " + path + " && node .' to start server.\n");
        });
    });
});